stages:
 - build
 
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
    
  script:
    - docker pull aminhoseinorg/loghme_backend:latest || true
    - docker build --cache-from aminhoseinorg/loghme_backend:latest -t backend_image .
    - docker tag backend_image aminhoseinorg/loghme_backend:latest
    - docker push aminhoseinorg/loghme_backend:latest
    
  only:
    - master