variables:
 - REG_ADDR: "aminhoseinorg/loghme_backend:latest"

stages:
 - build
 
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind

before-script:
    - docker login -u "codamin" -p "mydockeridcodamin"
    
  script:
    - docker pull $REG_ADDR || true
    - docker build --cache-from $REG_ADDR -t backend_image .
    - docker tag backend_image $REG_ADDR
    - docker push $REG_ADDR
    
  only:
    - master