variables:
  IMAGE_NAME: "loghme"
  TAG: "latest"
  
stages:
 - build
 
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
#   before_script:
    #docker login  

  script:
    - docker pull $IMAGE_NAME:$TAG || true
    - docker build --cache-from $IMAGE_NAME:$TAG --tag $IMAGE_NAME:$CI_COMMIT_SHA --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest
    
  only:
    - master