kind: Deployment
apiVersion: apps/v1
metadata:
  name: loghme-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loghme-backend
  template:
    metadata:
      labels:
        app: loghme-backend
    spec:
      containers:
        - name: loghme-backend
          image: aminhoseinorg/loghme-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 285m
              memory: 285Mi
            requests:
              cpu: 185m
              memory: 185Mi
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loghme-backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31885
  selector:
    app: loghme-backend