kind: Deployment
apiVersion: apps/v1
metadata:
  name: loghme-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loghme-backend
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loghme-backend
    spec:
      containers:
        - name: loghme-backend
          image: aminhoseinorg/loghme-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            # requests:
            #   cpu: 185m
            #   memory: 185Mi
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loghme-backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31885
  selector:
    app: loghme-backend